// packages/framework-solid/src/headless.ts
import { render } from 'solid-js/web';
import type { JSX } from 'solid-js';
import type { HeadlessAdapter } from '@mbsks/rspfx-core/headless';

export function createSolidAdapter<TProps extends Record<string, unknown>>(
  renderComponent: (props: TProps) => JSX.Element,
): HeadlessAdapter<TProps> {
  const disposers = new WeakMap<HTMLElement, () => void>();
  return {
    mount(root, props) {
      const prev = disposers.get(root);
      if (prev) prev();
      const dispose = render(() => renderComponent(props), root);
      disposers.set(root, dispose);
    },
    update(root, props) {
      const prev = disposers.get(root);
      if (prev) prev();
      const dispose = render(() => renderComponent(props), root);
      disposers.set(root, dispose);
    },
    unmount(root) {
      const d = disposers.get(root);
      if (d) {
        d();
        disposers.delete(root);
      }
    },
  };
}

// packages/framework-react/src/headless.ts
import { createRoot, type Root } from 'react-dom/client';
import type { ReactNode } from 'react';
import type { HeadlessAdapter } from '@mbsks/rspfx-core/headless';

const roots = new WeakMap<HTMLElement, Root>();

export function createReactAdapter<TProps extends Record<string, unknown>>(
  renderComponent: (props: TProps) => ReactNode,
): HeadlessAdapter<TProps> {
  return {
    mount(root, props) {
      let reactRoot = roots.get(root);
      if (!reactRoot) {
        reactRoot = createRoot(root);
        roots.set(root, reactRoot);
      }
      reactRoot.render(renderComponent(props));
    },
    update(root, props) {
      let reactRoot = roots.get(root);
      if (!reactRoot) {
        reactRoot = createRoot(root);
        roots.set(root, reactRoot);
      }
      reactRoot.render(renderComponent(props));
    },
    unmount(root) {
      const reactRoot = roots.get(root);
      if (reactRoot) {
        reactRoot.unmount();
        roots.delete(root);
      }
    },
  };
}
